/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import type {
  FileRoutesByPath,
  CreateServerFileRoute,
} from '@tanstack/react-start/server'
import {
  createServerRoute,
  createServerFileRoute,
} from '@tanstack/react-start/server'

import { ServerRoute as ApiTrpcSplatRouteImport } from './../../src/routes/api/trpc.$'

// Create/Update Routes

const rootRoute = createServerRoute()

const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-start/server' {
  interface FileRoutesByPath {
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './../../src/routes/api/trpc.$' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/trpc/$']['parentRoute'],
    FileRoutesByPath['/api/trpc/$']['id'],
    FileRoutesByPath['/api/trpc/$']['path'],
    FileRoutesByPath['/api/trpc/$']['fullPath'],
    unknown
  >
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}

export interface FileRoutesByTo {
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/trpc/$'
  id: '__root__' | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/api/trpc/$"
      ]
    },
    "/api/trpc/$": {
      "filePath": "api/trpc.$.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
