packages:
  - apps/*
  - packages/*

catalog:
  '@eslint-react/eslint-plugin': ^1.51.3
  '@t3-oss/env-core': ^0.13.4
  '@tanstack/react-query': ^5.76.1
  '@tanstack/react-query-devtools': ^5.76.1
  '@tanstack/react-router': ^1.121.0-alpha.22
  '@tanstack/react-router-devtools': ^1.121.0-alpha.22
  '@tanstack/react-start': ^1.121.0-alpha.26
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  '@vitejs/plugin-react': ^4.4.1
  dayjs: ^1.11.13
  dotenv: ^16.5.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.7.2
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  zod: ^3.24.4
catalogMode: prefer

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
