packages:
  - apps/*
  - packages/*

catalog:
  '@chakra-ui/react': ^3.21.1
  '@eslint-react/eslint-plugin': ^1.52.2
  '@iconify-json/material-symbols': ^1.2.29
  '@iconify-json/mdi': ^1.2.3
  '@iconify/react': ^6.0.0
  '@prisma/client': 6.9.0
  '@supabase/ssr': ^0.6.1
  '@supabase/supabase-js': ^2.50.3
  '@svgr/core': ^8.1.0
  '@svgr/plugin-jsx': ^8.1.0
  '@t3-oss/env-core': ^0.13.8
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/react-form': ^1.12.4
  '@tanstack/react-query': ^5.81.5
  '@tanstack/react-query-devtools': ^5.81.5
  '@tanstack/react-router': ^1.124.0
  '@tanstack/react-router-devtools': ^1.124.0
  '@tanstack/react-start': 1.124.1
  '@trpc/client': ^11.4.3
  '@trpc/react-query': ^11.4.3
  '@trpc/server': ^11.4.3
  '@trpc/tanstack-react-query': ^11.4.3
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.6.0
  cva: 1.0.0-beta.3
  dayjs: ^1.11.13
  dotenv: ^17.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  mime: ^4.0.7
  next-themes: ^0.4.6
  plaiceholder: ^3.0.0
  prisma: 6.9.0
  react: ^19.1.0
  react-dom: ^19.1.0
  react-icons: ^5.5.0
  superjson: ^2.2.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tldts: ^7.0.10

  typescript: ^5.8.3
  unplugin-icons: ^22.1.0
  uuid: ^11.1.0
  vite: ^7.0.2
  vite-tsconfig-paths: ^5.1.4
  zod: ^3.25.74
catalogMode: prefer

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
