import React from 'react'
import { apiGetMenuItems } from '@/controllers/menuItems'
import { apiGetMenu, apiGetMenus } from '@/controllers/menus'
import { apiGetRestaurants } from '@/controllers/restaurants'
import { apiGetSections } from '@/controllers/sections'
import Head from 'next/head'
import { AspectRatio, Box, Heading, Stack, Text } from '@chakra-ui/layout'
import PublicMenuLayout from '@/layouts/PublicMenu'
import BlurUpImage from '@/components/common/BlurUpImage'

export default function RestaurantMenu({
  slug,
  restaurant,
  menus,
  menu,
  sections,
  menuItems,
}) {
  return (
    <>
      <Head>
        <title>{restaurant?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PublicMenuLayout restaurant={restaurant} menus={menus}>
        <Box>
          <Stack>
            {/* <Box>
            <Heading as="h2" fontSize="2xl">
              Restaurant
            </Heading>
            <Text as="pre" fontSize="xs">
              {JSON.stringify(restaurant, null, 2)}
            </Text>
          </Box> */}
            <Box>
              <Heading as="h2" fontSize="3xl">
                {menu?.title}
              </Heading>
            </Box>
            <Box>
              {sections && (
                <Stack spacing="16">
                  {sections.map((section) => (
                    <Box key={section.id}>
                      <Heading as="h3" fontSize="2xl" mb="4">
                        {section.title}
                      </Heading>
                      {menuItems && (
                        <Stack spacing="4">
                          {menuItems
                            .filter((item) => item.sectionId === section.id)
                            .map((item) => (
                              <Box
                                key={item.id}
                                borderWidth="1px"
                                rounded="md"
                                overflow="hidden"
                                bg="white"
                                shadow="sm"
                              >
                                <AspectRatio
                                  ratio={16 / 9}
                                  mb="2"
                                  borderBottomWidth="1px"
                                >
                                  <BlurUpImage
                                    alt={item?.title || 'Menu item'}
                                    src={item?.image?.src}
                                    blurDataURL={item?.image?.blurDataURL}
                                    nextImageProps={{
                                      loading: 'lazy',
                                    }}
                                  />
                                </AspectRatio>
                                <Box p="4">
                                  <Heading as="h4" fontSize="lg">
                                    {item.title}
                                  </Heading>
                                  <Text fontWeight="semibold">
                                    ${item.price}
                                  </Text>
                                  <Text>{item.description}</Text>
                                </Box>
                              </Box>
                            ))}
                        </Stack>
                      )}
                    </Box>
                  ))}
                </Stack>
              )}
            </Box>
          </Stack>
        </Box>
      </PublicMenuLayout>
    </>
  )
}

export async function getServerSideProps({ params: { host }, query }) {
  const slug = query?.slug?.[0] || null

  const restaurants = await apiGetRestaurants({ customHost: host })
  const restaurant = restaurants?.[0]

  if (!restaurant) {
    return {
      notFound: true,
    }
  }
  const menus = await apiGetMenus({ restaurantId: restaurant.id })
  const menu = await apiGetMenu(slug || menus?.[0].id)
  const sections = await apiGetSections(menu?.id && { menuId: menu.id })
  const menuItems = await apiGetMenuItems(menu?.id && { menuId: menu.id })

  return {
    props: {
      menus,
      menu,
      restaurant,
      sections,
      menuItems,
    },
  }
}
